//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationToAccessWebServiceMethods.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.TestWebServiceSoap")]
    public interface TestWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name Firstname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Greet", ReplyAction="*")]
        ApplicationToAccessWebServiceMethods.ServiceReference.GreetResponse Greet(ApplicationToAccessWebServiceMethods.ServiceReference.GreetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Greet", ReplyAction="*")]
        System.Threading.Tasks.Task<ApplicationToAccessWebServiceMethods.ServiceReference.GreetResponse> GreetAsync(ApplicationToAccessWebServiceMethods.ServiceReference.GreetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GreetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Greet", Namespace="http://tempuri.org/", Order=0)]
        public ApplicationToAccessWebServiceMethods.ServiceReference.GreetRequestBody Body;
        
        public GreetRequest() {
        }
        
        public GreetRequest(ApplicationToAccessWebServiceMethods.ServiceReference.GreetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GreetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Firstname;
        
        public GreetRequestBody() {
        }
        
        public GreetRequestBody(string Firstname) {
            this.Firstname = Firstname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GreetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GreetResponse", Namespace="http://tempuri.org/", Order=0)]
        public ApplicationToAccessWebServiceMethods.ServiceReference.GreetResponseBody Body;
        
        public GreetResponse() {
        }
        
        public GreetResponse(ApplicationToAccessWebServiceMethods.ServiceReference.GreetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GreetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GreetResult;
        
        public GreetResponseBody() {
        }
        
        public GreetResponseBody(string GreetResult) {
            this.GreetResult = GreetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TestWebServiceSoapChannel : ApplicationToAccessWebServiceMethods.ServiceReference.TestWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestWebServiceSoapClient : System.ServiceModel.ClientBase<ApplicationToAccessWebServiceMethods.ServiceReference.TestWebServiceSoap>, ApplicationToAccessWebServiceMethods.ServiceReference.TestWebServiceSoap {
        
        public TestWebServiceSoapClient() {
        }
        
        public TestWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApplicationToAccessWebServiceMethods.ServiceReference.GreetResponse ApplicationToAccessWebServiceMethods.ServiceReference.TestWebServiceSoap.Greet(ApplicationToAccessWebServiceMethods.ServiceReference.GreetRequest request) {
            return base.Channel.Greet(request);
        }
        
        public string Greet(string Firstname) {
            ApplicationToAccessWebServiceMethods.ServiceReference.GreetRequest inValue = new ApplicationToAccessWebServiceMethods.ServiceReference.GreetRequest();
            inValue.Body = new ApplicationToAccessWebServiceMethods.ServiceReference.GreetRequestBody();
            inValue.Body.Firstname = Firstname;
            ApplicationToAccessWebServiceMethods.ServiceReference.GreetResponse retVal = ((ApplicationToAccessWebServiceMethods.ServiceReference.TestWebServiceSoap)(this)).Greet(inValue);
            return retVal.Body.GreetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApplicationToAccessWebServiceMethods.ServiceReference.GreetResponse> ApplicationToAccessWebServiceMethods.ServiceReference.TestWebServiceSoap.GreetAsync(ApplicationToAccessWebServiceMethods.ServiceReference.GreetRequest request) {
            return base.Channel.GreetAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApplicationToAccessWebServiceMethods.ServiceReference.GreetResponse> GreetAsync(string Firstname) {
            ApplicationToAccessWebServiceMethods.ServiceReference.GreetRequest inValue = new ApplicationToAccessWebServiceMethods.ServiceReference.GreetRequest();
            inValue.Body = new ApplicationToAccessWebServiceMethods.ServiceReference.GreetRequestBody();
            inValue.Body.Firstname = Firstname;
            return ((ApplicationToAccessWebServiceMethods.ServiceReference.TestWebServiceSoap)(this)).GreetAsync(inValue);
        }
    }
}
